import { ArrowLeft } from 'lucide-react';

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-purple-900 to-indigo-800">
      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Back button */}
        <a
          href="/"
          className="inline-flex items-center gap-2 text-indigo-300 hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Generator
        </a>

        {/* Content Card */}
        <div className="bg-white rounded-2xl shadow-2xl overflow-hidden">
          {/* Header */}
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-8 py-6">
            <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
            <p className="text-indigo-200 mt-2">Last updated: January 2025</p>
          </div>

          {/* Summary box */}
          <div className="mx-8 mt-8 p-4 bg-green-50 border-l-4 border-green-500 rounded-r-lg">
            <p className="text-green-800 font-medium">
              <strong>Summary:</strong> Indian Test Data Generator does NOT collect, store, or transmit any personal data. All data generation happens locally in your browser.
            </p>
          </div>

          {/* Content */}
          <div className="px-8 py-6 space-y-6">
            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Overview</h2>
              <p className="text-gray-600 leading-relaxed">
                Indian Test Data Generator is a web application and browser extension that generates fictional test data for developers and QA testers. This privacy policy explains how we handle information when you use our services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Data Collection</h2>
              <p className="text-gray-600 mb-3">We do NOT collect any data. Specifically:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-600">
                <li><strong>No personal information</strong> is collected</li>
                <li><strong>No browsing history</strong> is tracked</li>
                <li><strong>No form data</strong> you enter is captured or stored</li>
                <li><strong>No analytics or telemetry</strong> is sent to any server</li>
                <li><strong>No cookies</strong> are used for tracking</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">How It Works</h2>
              <p className="text-gray-600 mb-3">The application operates entirely within your browser:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-600">
                <li>Test data is generated locally using JavaScript algorithms</li>
                <li>No external API calls are made to generate data</li>
                <li>No data is sent to any remote server</li>
                <li>Your preferences are stored locally in your browser</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Chrome Extension Permissions</h2>
              <p className="text-gray-600 mb-3">The browser extension requests the following permissions:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-600">
                <li><strong>activeTab:</strong> To fill forms on the current page when you click the extension button</li>
                <li><strong>storage:</strong> To save your preferences locally (e.g., floating button toggle)</li>
                <li><strong>contextMenus:</strong> To provide right-click menu option for quick form filling</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Generated Data</h2>
              <p className="text-gray-600 mb-3">All data generated by this application is:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-600">
                <li>Completely fictional and randomly generated</li>
                <li>Not based on any real individuals</li>
                <li>Intended solely for testing and development purposes</li>
                <li>Not to be used for any real transactions or identity verification</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Third-Party Services</h2>
              <p className="text-gray-600">
                This application does not use any third-party services, analytics, or external APIs. The website is hosted on Vercel, which may collect basic server logs (IP addresses, access times) as part of their standard hosting service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Changes to This Policy</h2>
              <p className="text-gray-600">
                We may update this privacy policy from time to time. Any changes will be reflected on this page with an updated revision date.
              </p>
            </section>

            <section className="pt-4 border-t border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900 mb-3">Contact</h2>
              <p className="text-gray-600">
                If you have any questions about this privacy policy, please open an issue on our GitHub repository.
              </p>
            </section>
          </div>
        </div>

        {/* Footer */}
        <p className="text-center text-indigo-300 text-sm mt-8">
          Indian Test Data Generator - For Development & Testing Only
        </p>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
